# Generated by Django 5.2.17 on 2026-09-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
    ]
