# Generated by Django 5.2.17 on 2026-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/%Y/%m/'),
        ),
    ]
