# Generated by Django 5.2.17 on 2026-09-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_datasubmission_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='balance',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
