# Generated by Django 5.2.17 on 2026-09-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_remove_datacollection_price_per_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/'),
        ),
    ]
